version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: [ "dependencies" ]
    schedule:
      interval: "daily"

  # Gomod updates
  - package-ecosystem: "gomod"
    directory: "/"
    labels: [ "week" ]
    schedule:
      interval: "daily"
