version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: [ "dependencies" ]
    schedule:
      interval: "weekly"
      time: "03:00"
      timezone: "Europe/Berlin"

  # Gomod updates
  - package-ecosystem: "gomod"
    directory: "/"
    labels: [ "weekly" ]
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
