name: Lint

on:
  - pull_request:
  - push:
      branches:
      - 'main'

jobs:
  linters:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: 'go.mod'
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
      - name: alex
        uses: reviewdog/action-alex@v1
        with:
          reporter: github-pr-review
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          reporter: github-pr-review
